/**
This class implements simple cache for {{#crossLink "Bitmap"}}{{/crossLink}}.
@class BitmapCache
@module graphics
*/
class BitmapCache
{
    /**
    Construct cache object.
    @module this
    */
    function this() { }

    /**
    Returns bitmap object from the cache or loads it and store to this cache.
    @method getBitmap
    @param fileName {String} File name of the bitmap.
    @return {Bitmap}
    */
    function getBitmap(fileName) { }


}