/**
This class represents implementations of the MD5 hash algorithm.
@class MD5
@module crypto
*/
class MD5
{

    /**
    @method string
    @param text {String} Text to hash
    @return {Array}
    @example
        // hash text
        var hash = MD5.string("moscrif");
        // hashed value is: mM91EwVgpVzwIGlACITVOw==
        console<<hash.toString()<<"\n";
    */
    function string(text) { }


}